package com.github.vabshroo;

import com.github.vabshroo.orafile.exception.OrafileParseException;
import com.github.vabshroo.orafile.parser.OraFile;
import com.github.vabshroo.orafile.parser.OraFileParserContext;
import org.junit.Test;

/**
 * Created by IntelliJ IDEA
 *
 * @author chenlei
 * @date 2017/12/4
 * @time 22:06
 * @desc TestOrafileParser
 */
public class TestOrafileParser {

    @Test
    public void test() throws OrafileParseException {
        OraFileParserContext context = new OraFileParserContext("# tnsnames.ora Network Configuration File: /u01/app/oracle/product/12.2.0.1/dbhome_1/network/admin/tnsnames.ora\n" +
                "# Generated by Oracle configuration tools.\n" +
                "\n" +
                "\n" +
                "LISTENER_ST12201 =\n" +
                "  (ADDRESS_LIST =\n" +
                "    (ADDRESS = (PROTOCOL = TCP)(HOST = standalone)(PORT = 1521))\n" +
                "    (ADDRESS = (PROTOCOL = IPC)(HOST = standalone)(KEY = LISTENER_DG))\n" +
                "  )\n" +
                "\n" +
                "\n" +
                "\n" +
                "\n" +
                "ST12201DG2 =\n" +
                "  (DESCRIPTION =\n" +
                "    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.20.26 )(PORT = 1522))\n" +
                "    (CONNECT_DATA =\n" +
                "      (SERVER = DEDICATED)\n" +
                "      (SERVICE_NAME = ST12201DG2)\n" +
                "    )\n" +
                "   )\n" +
                "\n" +
                "ST12201 =\n" +
                "  (DESCRIPTION =\n" +
                "    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.20.114 )(PORT = 1522))\n" +
                "    (CONNECT_DATA =\n" +
                "      (SERVER = DEDICATED)\n" +
                "      (SERVICE_NAME = ST12201)\n" +
                "    )\n" +
                "   )\n" +
                "\n" +
                "ST12201DG =\n" +
                "  (DESCRIPTION =\n" +
                "    (ADDRESS = (PROTOCOL = TCP)(HOST = 192.168.20.19 )(PORT = 1522))\n" +
                "    (CONNECT_DATA =\n" +
                "      (SERVER = DEDICATED)\n" +
                "      (SERVICE_NAME = ST12201DG)\n" +
                "    )\n" +
                "   )");

        OraFile oraFile = new OraFile();
        oraFile.interpreter(context);
        System.out.println(oraFile.toString());
        System.out.println(oraFile.toOraFile());
    }

    @Test
    public void test1() throws OrafileParseException {
        OraFileParserContext context = new OraFileParserContext(
                "LISTENER_ST12201=" +
                        "    (ADDRESS_LIST=" +
                        "       (ADDRESS = ((PROTOCOL = TCP)(HOST = standalone)(PORT = 1521)))" +
                        "     )"
        );

        OraFile oraFile = new OraFile();
        oraFile.interpreter(context);
        System.out.println(oraFile.toString());
    }

    @Test
    public void test2() throws OrafileParseException {
        OraFileParserContext context = new OraFileParserContext("LISTENER_ST12201 =\n" +
                "  (ADDRESS_LIST =\n" +
                "    (ADDRESS = (PROTOCOL = TCP)(HOST = standalone)(PORT = 1521))\n" +
                "    (ADDRESS = (PROTOCOL = IPC)(HOST = standalone)(KEY = LISTENER_DG))\n" +
                "  )");

        OraFile oraFile = new OraFile();
        oraFile.interpreter(context);
        System.out.println(oraFile.toString());
    }

    @Test
    public void test3() throws OrafileParseException {
        OraFileParserContext context = new OraFileParserContext("a=b\nb=(c=d)(e=f)");

        OraFile oraFile = new OraFile();
        oraFile.interpreter(context);
        System.out.println(oraFile.toString());
    }

    @Test
    public void test4() throws OrafileParseException {
        OraFileParserContext context = new OraFileParserContext("a=b\nb=(c='d\\'\\#\\(\\)\\=')(e=f)");

        OraFile oraFile = new OraFile();
        oraFile.interpreter(context);
        System.out.println(oraFile.toString());
    }

    @Test
    public void test5() throws OrafileParseException {
        OraFileParserContext context = new OraFileParserContext("a=b\nb=(c='vvv\")(e=f)");

        OraFile oraFile = new OraFile();
        oraFile.interpreter(context);
        System.out.println(oraFile.toString());
    }

}
